language: python
sudo: false

python:
  - 3.6

branches:
  only:
    - master

install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install flake8
  - pip install -r requirements.txt
  - pip install pydash

script:
  - coverage run -m unittest discover
  - flake8 cmdbox

after_success:
  - coverage report
  - coveralls
