language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"
python:
  - '2.7'
  - '3.6'
  - '3.7'

install:
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - travis_rety pip install $PIP_DEPS
  - travis_rety pip install -r requirements.txt
  - travis_rety pip install -e

script:
  - py.test --pyargs xrdos --cov-report term-missing --cov=xrdos

after_success:
  - coverage report
  - coveralls
