language: python
sudo: false

python:
  - 3.6

branches:
  only:
    - master

install:
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements.txt

script:
  - py.test --pyargs xrdos --cov-report term-missing --cov=xrdos

after_success:
  - coverage report
  - coveralls
